# Generated by Django 3.2.9 on 2021-12-02 19:06

import attendence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('course_code', models.CharField(choices=[('CSE336', 'CSE336'), ('CSE335', 'CSE335'), ('CSE334', 'CSE334'), ('CSE332', 'CSE332'), ('CSE331', 'CSE331')], max_length=255)),
                ('qr', models.ImageField(blank=True, upload_to=attendence.models.qr_code_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
